# Generated by Django 6.0.6 on 2026-07-07 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='e.g. Lagos, Nigeria', max_length=120)),
                ('quote', models.TextField(max_length=600)),
                ('rating', models.PositiveSmallIntegerField(choices=[(5, '5 — Excellent'), (4, '4 — Very Good'), (3, '3 — Good'), (2, '2 — Fair'), (1, '1 — Poor')], default=5)),
                ('is_approved', models.BooleanField(default=False, help_text='Only approved testimonials show on the homepage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
