# Generated by Django 6.0.6 on 2026-07-05 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('oxygen', 'Oxygen'), ('medication', 'Medication'), ('equipment', 'Medical Equipment'), ('blood_product', 'Blood Product')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('unit_of_measure', models.CharField(default='units', max_length=50)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_supplies', to='facilities.facility')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supply_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medical Supplies',
                'ordering': ['category', 'supply_name'],
            },
        ),
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], max_length=3)),
                ('units_available', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_stocks', to='facilities.facility')),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_stock_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['blood_type'],
                'unique_together': {('facility', 'blood_type')},
            },
        ),
    ]
