# Generated by Django 6.0.6 on 2026-07-05 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('blood', 'Blood'), ('oxygen', 'Oxygen'), ('medication', 'Medication'), ('equipment', 'Medical Equipment')], max_length=20)),
                ('blood_type', models.CharField(blank=True, choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], help_text='Required if request type is blood', max_length=3, null=True)),
                ('units_needed', models.PositiveIntegerField(default=1)),
                ('supply_name', models.CharField(blank=True, help_text='Required for medication or equipment requests', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location_text', models.CharField(help_text='Describe your location (e.g. Surulere, Lagos)', max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100, verbose_name='Local Government Area')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('urgency', models.CharField(choices=[('critical', 'Critical — Life Threatening'), ('urgent', 'Urgent'), ('normal', 'Normal')], default='urgent', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('broadcasting', 'Broadcasting to Facilities'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=15)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('waived', 'Waived'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_at', models.DateTimeField(blank=True, null=True)),
                ('fulfilled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfilled_requests', to='facilities.facility')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.CharField(choices=[('pending', 'Awaiting Response'), ('available', 'Available'), ('unavailable', 'Unavailable')], default='pending', max_length=15)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_broadcasts', to='facilities.facility')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='emergency_requests.emergencyrequest')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('request', 'facility')},
            },
        ),
    ]
