# Generated by Django 6.0.6 on 2026-07-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('broadcasting', 'Broadcasting to Facilities'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=15),
        ),
    ]
